### ISSUE TITLE
[Bug] consecutive tests with the same resource names show intermittent failures

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/chainsaw#1864] opened 2024-08-15 02:09 UTC
### chainsaw version Version

v0.2.8

### Description

When there are several consecutive tests which use the same resource names for cluster resources, there are intermittent failures.

Setting unique resource names works.

Trying to use the Kubernetes `generateName` fails with an error stating a `name` is required.

### Steps to reproduce

See above.

### Expected behavior

Fix cleanup logic across tests.

Support `create` with `generateName`, or provide some way to automatically add a unique suffix to names.

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment] 2024-08-16 17:04
Thanks for reporting @JimBugwadia.
Do you have an example ? Are test running concurrently ?

**Comment by eddycharly** [comment] 2024-12-04 09:01
Closing, cannot reproduce. Please reopen if needed.

**Closed by eddycharly** 2024-12-04 09:01 UTC
Labels: bug
