### ISSUE TITLE
[Bug] Wait Condition not working with value provided

### ISSUE THREAD

**Issue by johnathan-sq** [kyverno/chainsaw#1110] opened 2024-03-13 11:31 UTC
### chainsaw version Version

v0.1.8

### Description

I have a test case which creates a deployment and am trying to wait for a deployment to become Available=True. 

I think the PR https://github.com/kyverno/chainsaw/pull/981 has broken the functionality, as when I reverted it (locally), compiled and ran it, it worked fine. 

When I run the command locally (the one which it hangs on)

`kubectl wait deployments.v1.apps --for=condition=available="True" nginx-deployment -n chainsaw-clever-quagga --timeout=-1s`

It will work fine and resolve.

### Steps to reproduce

1. Run the code below and the COMMAND for waiting will hang.

```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: quick-start
spec:
  steps:
  - try:
    # first operation: create the config map
    - apply:
        resource:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            labels:
              app: nginx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80
    - wait:
        apiVersion: apps/v1
        kind: Deployment
        name: nginx-deployment
        timeout: 1m
        for:
          condition:
            name: available
            value: "True"
    # second operation: verify the config map exists and contains the expected data
    - assert:
        resource:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            labels:
              app: nginx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80
```

### Expected behavior

1. The command resolves when the condition is met. 

### Screenshots

![Screenshot 2024-03-13 at 10 29 45 pm](https://github.com/kyverno/chainsaw/assets/121202136/ffae74d3-57af-4836-8215-c80357200594)

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment] 2024-03-13 14:26
The message is not correct but it works correctly, will try to come up with a solution.

**Comment by eddycharly** [comment] 2024-03-13 14:27
Thanks for reporting

**Comment by johnathan-sq** [comment] 2024-03-13 22:13
You mean it works correctly under the hood but doesn't report the finding correctly?

**Comment by eddycharly** [comment] 2024-03-13 22:24
@johnathan-sq yes

what we do is:
- set a long timeout when invoking `kubectl` (`--timeout=-1s` uses a negative timeout, equivalent to one week)
- but the operation has the timeout you set in the yaml

In the end the timeout you configure is applied at the operation level but not in the `kubectl` command itself, this way we don't need to keep both in sync and avoid races.

Except the report looking incorrect it behaves as expected.

**Comment by eddycharly** [comment] 2024-03-14 13:11
> Do you know why the quotes were added to the wait cmd's.

this is to differentiate from an empty string and the default value (`true`)

**Comment by eddycharly** [comment] 2024-03-14 13:14
> There seems to be a problem with the go exec command which is passing the double strings which looks like it's running but is potentially hanging in the background.

add a catch block to dump the resources you are interested in to verify how it looks like

**Comment by johnathan-sq** [comment] 2024-03-15 04:43
I tried a few things but I haven't been able to figure it out. I know that removing the quotes from the `%s` [here](https://github.com/kyverno/chainsaw/blob/7ce628b6cc4fb90218c628205ead26e8ad575f2f/pkg/runner/kubectl/wait.go#L65): seems to fix it. 

The kubectl command it's running seems good too (copying and pasting this yields a good result), got this using `ps aux | grep kubectl` 

Will keep looking into it, but not much success as of yet.

**Comment by johnathan-sq** [comment] 2024-04-02 21:17
Tried to play around with it a little bit, it seems like when you add a `-v=8` (which will output to stderr) it seems to log output to `stderr`  but when the quotes are in will not output to `stdout`.

**Comment by eddycharly** [comment] 2024-04-02 21:23
@johnathan-sq i will give it a look tomorrow, is the sample in the PR description reproducing your issue ?

**Comment by johnathan-sq** [comment] 2024-04-03 03:36
Yep, the sample will reproduce the issue as expected.

**Comment by johnathan-sq** [comment] 2024-04-03 10:31
Thanks for the PR @eddycharly, (sorry if I'm jumping the gun if you haven't finished) I just gave it a go and it doesn't seem to work for me. I still get the same issue where it hangs.

**Comment by eddycharly** [comment] 2024-04-03 12:14
@johnathan-sq i investigated the issue and the quotes seem to be the problem :(

**Comment by eddycharly** [comment] 2024-04-03 12:45
@johnathan-sq it will be fixed in #1142 https://github.com/kyverno/chainsaw/pull/1142

**Closed** 2024-04-03 13:00 UTC
Labels: bug, good first issue, Contribfest

**Comment by johnathan-sq** [comment] 2024-04-03 20:34
Awesome, I thought that may have been the case, I gave it a good go to try figure out why quotes was breaking it but wasn't able to figure it out. Appreciate the effort though.

**Comment by eddycharly** [comment] 2024-04-03 21:58
Quotes are not an issue when the command is run in a shell because the shell processes the quotes and ultimately removes them.

When chainsaw runs the command it doesn't go through a shell and therefore quotes are not processed and removed. Basically we don't need the quotes when the command is invoked by chainsaw.
